version: "3.9"
services:
  foo:
    build:
      context: ../go-echo
      dockerfile: ../go-echo/Dockerfile.echo
    container_name: foo
    expose:
      - 9000
    environment:
      HOST_ID: foo-1
    networks:
      - skynet
  bar:
    build:
      context: ../go-echo
      dockerfile: ../go-echo/Dockerfile.echo
    container_name: bar
    expose:
      - 9000
    environment:
      HOST_ID: bar-1
    networks:
      - skynet
  nginx:
    image: nginx:1.25.1-alpine
    container_name: nginx
    ports:
      - "9999:8080"
    volumes:
      - "${PWD}/nginx.conf:/etc/nginx/nginx.conf"
      - "${PWD}/index.html:/var/www/xyz/index.html"
    networks:
      - skynet
    depends_on:
      - foo
      - bar
networks:
  skynet:
